// <auto-generated />
using System;
using Canarytype_alpha3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Canarytype_alpha3.Migrations
{
    [DbContext(typeof(CanaryTypeDBContext))]
    [Migration("20260313171713_add verification codes")]
    partial class addverificationcodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Canarytype_alpha3.Data.MatchInfo", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<string>("Player1Submissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player1SubmissionsRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int");

                    b.Property<string>("Player2Submissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player2SubmissionsRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("matchDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RoomId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("MatchInfoTable", (string)null);
                });

            modelBuilder.Entity("Canarytype_alpha3.Data.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("UsersTable", (string)null);
                });

            modelBuilder.Entity("Canarytype_alpha3.Data.UserSubmissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("int");

                    b.Property<string>("rawTypingSpeedPerSecond")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typingSpeedPerSecond")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId");

                    b.ToTable("UsersSubmissionsTable");
                });

            modelBuilder.Entity("Canarytype_alpha3.Data.VerificationCodes", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OTP")
                        .HasColumnType("int");

                    b.HasKey("UserEmail");

                    b.ToTable("VerificationCodes", (string)null);
                });

            modelBuilder.Entity("Canarytype_alpha3.Data.MatchInfo", b =>
                {
                    b.HasOne("Canarytype_alpha3.Data.UserInfo", "Player1")
                        .WithMany("MatchesAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Canarytype_alpha3.Data.UserInfo", "Player2")
                        .WithMany("MatchesAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("Canarytype_alpha3.Data.UserSubmissions", b =>
                {
                    b.HasOne("Canarytype_alpha3.Data.UserInfo", "UserInfo")
                        .WithMany("UserSubmissions")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("Canarytype_alpha3.Data.UserInfo", b =>
                {
                    b.Navigation("MatchesAsPlayer1");

                    b.Navigation("MatchesAsPlayer2");

                    b.Navigation("UserSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
